src/AppBundle/Entity/Currency.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Currency
 *
 * @ORM\Table(name="currency")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\CurrencyRepository")
 */
class Currency
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string")
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="title_alias", type="string")
     */
    private $title_alias;

    /**
     * @var float
     *
     * @ORM\Column(name="sell_rate", type="float")
     */
    private $sell_rate;

    /**
     * @var float
     * @ORM\Column(name="buy_rate", type="float")
     */
    private $buy_rate;

    /**
     * @var \DateTime
     * @ORM\Column(name="start_date", type="datetime")
     */
    private $start_date;
    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Currency
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set titleAlias
     *
     * @param string $titleAlias
     *
     * @return Currency
     */
    public function setTitleAlias($titleAlias)
    {
        $this->title_alias = $titleAlias;

        return $this;
    }

    /**
     * Get titleAlias
     *
     * @return string
     */
    public function getTitleAlias()
    {
        return $this->title_alias;
    }

    /**
     * @return float
     */
    public function getSellRate(): float
    {
        return $this->sell_rate;
    }

    /**
     * @param float $sell_rate
     */
    public function setSellRate(float $sell_rate)
    {
        $this->sell_rate = $sell_rate;
    }

    /**
     * @return float
     */
    public function getBuyRate(): float
    {
        return $this->buy_rate;
    }

    /**
     * @param float $buy_rate
     */
    public function setBuyRate(float $buy_rate)
    {
        $this->buy_rate = $buy_rate;
    }

    /**
     * @return \DateTime
     */
    public function getStartDate()
    {
        return $this->start_date;
    }

    /**
     * @param \DateTime $start_date
     */
    public function setStartDate($start_date)
    {
        $this->start_date = $start_date;
    }

}

src/AppBundle/Controller/CurrencyController.php
<?php

namespace AppBundle\Controller;

use phpQuery;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Response;
use AppBundle\Libs\CourseManager;

class CurrencyController extends Controller
{
    /**
     * @Route("/", name="homepage")
     * @return Response
     */
    public function showCourseAction()
    {
        $courses = $this->getDoctrine()
            ->getRepository('AppBundle:Currency')
            ->findAll();

        $course_manager = $this->getCourseManager();

        if (empty($courses)) {
            $course_manager->saveCourseRates();
            $courses = $course_manager->getCoursesDataFromDB();
        }

        return $this->render('@App/index.html.twig', array(
            'courses' => $courses,
        ));
    }

    /**
     * @Route("/update_schedule")
     * @Method("GET")
     */
    public function updateCourseSchedule()
    {
        $course_manager = $this->getCourseManager();
        $course_manager->UpdateCourseSchedule();

        return new Response(json_encode([
            'success' => $success ?? true
        ]));
    }


    public function getCourseManager()
    {
        return new CourseManager($this->getDoctrine()->getManager());
    }

}

src/AppBundle/Tests/Controller/ValutaControllerTest.php
<?php

namespace AppBundle\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class ValutaControllerTest extends WebTestCase
{
    public function testShowkurs()
    {
        $client = static::createClient();

        $crawler = $client->request('GET', '/showKurs');
    }

}

src/AppBundle/Resources/views/index.html.twig
{% extends '::base.html.twig' %}

{% block body %}

    <div align="center" class="col-lg-offset-3 col-lg-6 col-lg-offset-3">
        <h2 id="question">Хочешь посмотреть курс валют ?!</h2>
        <button class="btn btn-danger" id="load_btn">ДА</button>

        <div class="table-responsive" style="display: none" id="course_table">

            <h1 id="fresh_greeting">Свежайший курс валют</h1>

            <table class="table table-bordered table-striped">
                <thead>
                <tr style="background: cornflowerblue">
                    <th>Полное название</th>
                    <th>Аббревиатура</th>
                    <th>Цены покупки</th>
                    <th>Цены продажи</th>
                    <th>Время Обновления</th>
                </tr>
                </thead>
                <tbody>
                {% for valut in courses %}
                    <tr style="background: #ffcc00;">
                        <td>{{ valut.title }}</td>
                        <td>{{ valut.titleAlias }}</td>
                        <td>{{ valut.buyRate }}</td>
                        <td>{{ valut.sellRate }}</td>
                        <td>{{ valut.startDate|date('Y-m-d H:i:s') }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <button class="btn-danger" id="update_btn" style="display: none">Обновить таблицу</button>
        </div>
    </div>

{% endblock %}